USE reddit;

CREATE TABLE IF NOT EXISTS owner(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL,
vote INT
);

CREATE TABLE IF NOT EXISTS post(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
url VARCHAR(100),
timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
score INT,
owner_id INT NOT NULL,
FOREIGN KEY (owner_id) REFERENCES owner (id)
);


